package com.github.martyanovav.otuskotlin.fitbridge.common.models

enum class FBCommand {
    NONE,
    TRAINER_PROFILE_CREATE_OR_UPDATE,
    TRAINER_PROFILE_READ_OWN,
    CLIENT_CARD_CREATE,
    CLIENT_CARD_READ,
    CLIENT_CARD_UPDATE,
    CLIENT_CARD_ARCHIVE,
    CLIENT_CARD_LIST,
    TRAINING_PLAN_CREATE,
    TRAINING_PLAN_READ,
    TRAINING_PLAN_UPDATE,
    TRAINING_PLAN_ARCHIVE,
    TRAINING_PLAN_GENERATE_PUBLIC_LINK,
    TRAINING_PLAN_CLOSE_PUBLIC_LINK,
    TRAINING_PLAN_READ_COMPLETION_STATUS,
    DASHBOARD_GET_TRAINER_SUMMARY,
    PUBLIC_PLAN_OPEN_BY_TOKEN,
    PUBLIC_PLAN_MARK_COMPLETION
}
