@startuml C4_Context
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

title Контекстная диаграмма - FitBridge

Person(client, "Клиент", "Person, Organization")
Person(coach, "Тренер", "Person, Organization")
Person(support, "Оператор поддержки", "Employee")
Person(owner, "Владелец студии", "Employee")
Person(devops, "DevOps-инженер", "Employee")

System_Ext(keycloak, "Keycloak")
System(fitbridge, "FitBridge", "Software System")

Rel(client, keycloak, "Аутентифицируется, получает JWT...")
Rel(coach, keycloak, "Аутентифицируется, получает JWT...")

Rel(client, fitbridge, "Ведет дневник и доступы...")
Rel(fitbridge, client, "Отправляет уведомления...")

Rel(coach, fitbridge, "Назначает программы...")
Rel(fitbridge, coach, "Отправляет уведомления...")

Rel(support, fitbridge, "Разбирает обращения...")
Rel(owner, fitbridge, "Управляет студией...")
Rel(devops, fitbridge, "Мониторинг и эксплуатация...")

@enduml