@startuml C4_Component
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

title Диаграмма компонентов - FitBridge API

Container(post_api, "POST Full API...")

System_Ext(db, "Application DB...")
System_Ext(monitoring, "Monitoring", "Software System")
System_Ext(notification_provider, "Notification Provider...")

Container_Boundary(fitbridge_api_bound, "FitBridge API...") {
    Component(client_api, "Client API...")
    Component(coach_api, "Coach API...")
    Component(domain_models, "Domain Models...")
    Component(log_client, "LogClient API...")

    Component(ktor_routing, "Ktor Routing...")

    Component(domain_services, "Domain Services...")
    Component(persistence, "Persistence Gateway...")
    Component(audit, "Audit Component...")

    Component(access_rules, "Access Rules...")
    Component(notification_adapter, "Notification Adapter...")
}

Rel(post_api, ktor_routing, "POST API calls...")

Rel(ktor_routing, client_api, "Маппит в...")
Rel(ktor_routing, coach_api, "Маппит в...")

Rel(client_api, domain_models, "Преобразует в...")
Rel(coach_api, domain_models, "Преобразует в...")

Rel(ktor_routing, domain_models, "Uses...")
Rel(ktor_routing, domain_services, "Вызывает домен...")
Rel(ktor_routing, persistence, "Инициализирует...")
Rel(ktor_routing, audit, "Uses...")

Rel(domain_services, access_rules, "Uses...")
Rel(domain_services, persistence, "Uses...")
Rel(domain_services, notification_adapter, "Uses...")

Rel(persistence, db, "Reads/Writes...")

Rel(audit, log_client, "Сериализует аудит в...")
Rel(audit, monitoring, "Публикует аудит в...")

Rel(notification_adapter, notification_provider, "Sends...")

@enduml