@startuml C4_Container
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

title Диаграмма контейнеров - FitBridge

Person(user, "Пользователь", "Person")

System_Ext(keycloak, "Keycloak")
System_Ext(notification_provider, "Notification Provider")
System_Ext(monitoring, "Мониторинг", "Software System")

System_Boundary(frontend, "Фронтенд FitBridge...") {
    Container(static_hosting, "Static Hosting")
    Container(web_ui, "Web UI")
    Container(coach_app, "CoachApp")
    Container(client_app, "ClientApp")
}

System_Boundary(backend, "Бэкенд FitBridge...") {
    ContainerDb(db_fitbridge, "Application DB")
    ContainerDb(db_reports, "Application DB")
    Container(fitbridge_api, "FitBridge API")
    Container(reports_api, "Reports API")
}

Container(api_gateway, "API Gateway")

Rel(user, keycloak, "Запрос аутентификации...")
Rel(keycloak, user, "Предоставляет JWT...")

Rel(notification_provider, user, "Отправляет приглашения...")
Rel(user, static_hosting, "Открывает fitbridge.ru...")
Rel(static_hosting, web_ui, "Публикует [HTTP]")

Rel(user, web_ui, "Дневник, программы, отчеты...")
Rel(user, coach_app, "Дневник, программы, отчеты...")
Rel(user, client_app, "Дневник, программы, отчеты...")

Rel(web_ui, api_gateway, "Makes API calls...")
Rel(coach_app, api_gateway, "Makes API calls...")
Rel(client_app, api_gateway, "Makes API calls...")

Rel(api_gateway, fitbridge_api, "Redirect API calls...")
Rel(api_gateway, reports_api, "Redirect API calls...")

Rel(fitbridge_api, db_fitbridge, "R/W...")
Rel(reports_api, db_reports, "R/W...")

Rel(fitbridge_api, notification_provider, "Отправка уведомлений...")

Rel(api_gateway, monitoring, "Направляют логи, метрики, трейсы...")
Rel(fitbridge_api, monitoring, "Направляют логи, метрики, трейсы...")
Rel(reports_api, monitoring, "Направляют логи, метрики, трейсы...")

@enduml