# Минимальная версия инфраструктуры на базе:
# GreptimeDB, Fluent Bit, Envoy, Keycloak.

# Адреса:
# Приложение доступно по http://localhost:8080 через Envoy.
# Логи и метрики доступны через http://localhost:4000/dashboard/.
# Управление пользователями доступно по http://localhost:8080/admin.
services:
  app:
    extends:
      file: app-base.yml
      service: app-base
    depends_on:
      - fluent-bit
      - envoy

  fluent-bit:
    extends:
      file: fluent-bit-base.yml
      service: fluent-bit-base
    depends_on:
      greptimedb:
        condition: service_healthy

  greptimedb:
    extends:
      file: greptimedb-base.yml
      service: greptimedb-base

  envoy:
    extends:
      file: envoy-base.yml
      service: envoy-base

  keycloak:
    extends:
      file: keycloak-base.yml
      service: keycloak-base

volumes:
  greptimedb-data:

networks:
  backend-network:
    driver: bridge
