services:
  greptimedb-base:
    image: greptime/greptimedb:v0.14.4
    container_name: greptimedb
    command:
      - standalone
      - start
      - --http-addr
      - 0.0.0.0:4000
      - --rpc-bind-addr
      - 0.0.0.0:4001
    ports:
      - "4000:4000"
      - "4001:4001"
      - "4002:4002"
      - "4003:4003"
    volumes:
      - greptimedb-data:/tmp/greptimedb/
    healthcheck:
      test: ["CMD-SHELL", "status=$$(/usr/bin/curl --silent --show-error --output /dev/null --write-out '%{response_code}' --request GET http://127.0.0.1:4000/health) && [ \"$$status\" = 200 ]"]
      interval: 5s
      timeout: 3s
      retries: 12
      start_period: 10s
    networks:
      - backend-network
