input {
  kafka {
    bootstrap_servers => "${BOOTSTRAP_SERVERS}"
    topics => "fit-bridge-logs"
    codec => "json"
  }
}

filter {
  if [type] == "nginx" {
    mutate {
      add_field => [ "fitbridge_field", "Hello FitBridge" ]
    }
  }
}

output {
  http {
    url => "http://greptimedb:4000/v1/ingest?db=public&table=logs_fit_bridge&pipeline_name=greptime_identity"
    http_method => "post"
    format => "json"
  }
}
