input {
  kafka {
    bootstrap_servers => "${BOOTSTRAP_SERVERS}"
    topics => "fit-bridge-logs"
    codec => "json"
  }
}

filter {
  if [type] == "nginx" {
    mutate {
      add_field => [ "fitbridge_field", "Hello FitBridge" ]
    }
  }
}

output {
  opensearch {
    id => "os_out_fit_bridge_logs"
    hosts => ["https://opensearch:9200"]
    user => "admin"
    password => "admin"
    ssl => true
    ssl_certificate_verification => false
    index => "logs-fit-bridge-%{+YYYYMMdd}"
  }
}
