[SERVICE]
  log_level    info
  flush           1
  HTTP_Server  On
  HTTP_Listen  0.0.0.0
  HTTP_PORT    2020
  Health_Check On
  Parsers_File parsers.conf

[INPUT]
  Name          forward
  Tag           app.logs
  Listen        0.0.0.0
  Port          24224

[FILTER]
  Name parser
  Match *
  Key_Name log
  Parser logback
  Reserve_Data True

[OUTPUT]
  Name            http
  Match           *logs
  Host            ${greptimedb_host}
  Port            4000
  Uri             /v1/ingest?db=public&table=app_logs&pipeline_name=greptime_identity
  Format          json
  http_User       ${greptimedb_user}
  http_Passwd     ${greptimedb_pass}


[INPUT]
  Name          cpu
  Tag           cpu.load

[OUTPUT]
  Name            http
  Match           cpu.load
  Host            ${greptimedb_host}
  Port            4000
  Uri             /v1/ingest?db=public&table=cpu_load&pipeline_name=greptime_identity
  Format          json
  http_User       ${greptimedb_user}
  http_Passwd     ${greptimedb_pass}
