services:
  liquibase-training:
    image: ghcr.io/${GHCR_USERNAME}/fitbridge-migration-pg-training:${APP_VERSION:-latest}

  training-service:
    build: !reset null
    image: ghcr.io/${GHCR_USERNAME}/fitbridge-training-service:${APP_VERSION:-latest}

  frontend:
    build: !reset null
    image: ghcr.io/${GHCR_USERNAME}/fitbridge-frontend:${APP_VERSION:-latest}
