ktor:
  development: true
  deployment:
    port: 8081
  watch:
    - classes
    - resources
  application:
    modules:
      - "com.github.martyanovav.otuskotlin.fitbridge.training.app.ktor.ApplicationJvmKt.moduleJvm"
